name: ffbayes
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pymc>=5.0
  - pandas>=1.5
  - numpy>=1.20
  - matplotlib>=3.5
  - scikit-learn>=1.0
  - alive-progress>=3.0
  - pytest>=7.0
  - jupyter
  - ipykernel
  - pip
  - pip:
    - nfl-data-py>=0.2
    - fuzzywuzzy
    - python-levenshtein
